streams:
  camera:
    - v4l2:device?video=/dev/video1&input_format=mjpeg&video_size=1280x720&framerate=30

api:
  listen: ":1984"

webrtc:
  listen: ":8555"
  candidates:
    - stun:8555

log:
  level: info