streams:
  camera:
    - "video /dev/video1"
    - "ffmpeg:camera#video=h264_v4l2m2m"
  camera_low:
    - "ffmpeg:camera#video=h264_v4l2m2m#video_bitrate=1500"

api:
  listen: ":1984"

webrtc:
  listen: ":8555"
  candidates:
    - stun:8555

log:
  level: warn